// Sigma / peak male / lekko wulgarne komentarze pogodowe (PL).
//
// GENEROWANE Z ŹRÓDŁA PRAWDY: widget/SigmaJokes.kt — trzymaj oba identyczne.
//
// Twardy limit 50 znaków na linię i to realne ograniczenie, nie preferencja:
// to trafia na footer widgetu (jedna linia, ellipsize), a najwęższa szerokość,
// przy której widget go jeszcze rysuje, mieści ~48 znaków monospace. Dłuższe
// i puenta jest tym, co zamienia się w "…". Pilnuje tego test —
// android/app/src/test/.../WidgetContentTest.kt.
import type { WeatherKind } from "./wmo";

const SIGMA: Record<WeatherKind | "night", string[]> = {
  sun: [
    "słońce grzeje, beta narzeka na UV",
    "+25°C, w sam raz na trening klatki, nie na płacz",
    "grindset weather. wychodzisz albo zostajesz nikim",
    "ładna pogoda, a ty siedzisz w chacie jak cuck",
    "słońce świeci mocniej niż twoja kariera",
    "UV index wyższy niż twoja pewność siebie",
    "sigma się opala i planuje imperium, ty drzemkę",
    "+30°C na dworze, +2 na koncie, based",
    "witamina D za darmo, silnej woli nie rozdają",
    "idealna pogoda na cardio, wybierasz kanapę",
    "słońce w zenicie, ambicje w fazie planowania",
    "giga słonecznie, zero wymówek, ogarnij się",
    "cień też trzeba zasłużyć. najpierw wyjdź",
    "słońce nie pyta czy masz humor. wstawaj",
    "piękny dzień na bycie kimś. spróbuj",
    "klimatyzacja to cope. zahartuj się",
    "opalenizna gratis, charakter w abonamencie",
    "słońce non stop, a ty w trybie oszczędzania",
    "taki dzień zdarza się rzadziej niż twój plan",
    "gorąco. wypij wodę zanim padniesz na patio",
    "SPF 50 na skórę, zero SPF na wymówki",
    "dzień idealny. wymówka też musi być idealna",
    "słońce w kalendarzu, ty w powiadomieniach",
    "sigma łapie promienie, beta łapie doomscroll",
    "ciepło jak w piekle, ale piekło ma lepszy plan",
  ],
  partly: [
    "chmury się nie mogą zdecydować, jak twoja ex",
    "50/50, jak twoje szanse u tamtej z insta",
    "pół-jasno, pół-gówno, klasyk",
    "pogoda mid, jak twój bench press",
    "częściowe zachmurzenie, jak motywacja po 10",
    "50% szans na deszcz, 100% że nic nie zrobisz",
    "chmury przelotne, plany życiowe jeszcze bardziej",
    "niebo w trybie demo, pełna wersja płatna",
    "pogoda 'może', jak twoje 'jutro na siłkę'",
    "niebo nie wie czego chce. macie coś wspólnego",
    "słońce wychodzi, chowa się, wychodzi. relatable",
    "pogoda na 'zobaczymy'. twój ulubiony tryb",
    "trochę słońca, trochę chmur, zero decyzji",
    "niebo gra na zwłokę tak jak ty z tym mailem",
    "mid weather, mid dzień, mid ty. napraw jedno",
    "chmury przychodzą i idą. deadline zostaje",
    "połowa nieba zajęta, połowa planów też",
    "raz cień, raz słońce. jak twoja dyscyplina",
    "pogoda kompromisowa. życie nie musi być",
    "ani ładnie, ani brzydko. jak twój tydzień",
    "niebo w kratkę, grafik w kratkę, spójnie",
    "50% chmur, 100% potencjału zmarnowanego",
    "zmienne zachmurzenie, niezmienne wymówki",
    "słońce zagląda i ucieka jak twoja pewność",
  ],
  cloud: [
    "szaro-buro, idealnie pod depresję i redbulla",
    "niebo zachmurzone jak myśli o poniedziałku",
    "pochmurno. beta w domu, sigma i tak wychodzi",
    "chmury gęste jak wymówki kumpla",
    "zachmurzenie jak brak planu na przyszłość",
    "szaro jak twój Discord status od trzech dni",
    "niebo w kolorze nastroju o 6 rano",
    "chmury nisko, standardy jeszcze niżej",
    "zachmurzenie jak motywacja — teoretycznie jest",
    "niebo bez słońca, ty bez planu, wtorek rel",
    "szaro. idealna pogoda żeby nikt cię nie widział",
    "chmury nie przepuszczają światła ani wymówek",
    "pochmurno, ale siłka ma dach. żadnej litości",
    "niebo ma filtr grayscale. twój dzień też",
    "bez słońca, bez cienia, bez charakteru",
    "beżowy dzień. dodaj kontrast albo zostań tłem",
    "chmury na całość. ty na pół gwizdka",
    "szaro jak Excel którego nie otwierasz",
    "pogoda bez opinii. w przeciwieństwie do ciebie",
    "niebo zamknięte na klucz, jak siłownia w głowie",
    "pochmurnie. świat ci nie kibicuje, i dobrze",
    "chmury po horyzont, wymówki po sufit",
    "szary dzień to nie wyrok, to tło pod robotę",
    "niebo dziś na minimalizmie. ty na minimum",
  ],
  fog: [
    "mgła gęstsza niż twój wywód po piątym piwie",
    "visibility 10m, jak twoje plany życiowe",
    "mgła. idealna na zniknięcie bez tłumaczenia",
    "nic nie widać, jak przyszłość bez planu B",
    "widoczność zero, motywacja też, nogi idą",
    "mgła jak twój umysł przed kawą — i po niej",
    "gęsto jak po 'od jutra zaczynam' po raz setny",
    "mgła zasłania horyzont, wymówki resztę",
    "gęsta mgła, rzadkie postanowienia noworoczne",
    "mgła. jedziesz wolniej, myślisz tak samo",
    "nie widać dalej niż na tydzień. jak w planach",
    "mgła zjadła horyzont. ambicje już wcześniej",
    "biała ściana. za nią dalej twoje obowiązki",
    "widać 10 metrów, wystarczy na pierwszy krok",
    "mgła nie trwa wiecznie. twoje odkładanie może",
    "świat na rozmyciu 20px. ładne, bezużyteczne",
    "mgła, cisza, zero wymówek. idealne na bieg",
    "nic nie widać, więc nikt nie oceni twojej formy",
    "mgła gęsta jak twój wątek myślowy o 3 w nocy",
    "we mgle każdy wygląda tajemniczo. korzystaj",
    "widoczność jak twoja wizja na pięć lat",
    "mgła rozejdzie się sama. reszta nie",
    "szara zupa. wejdź w nią zanim ostygnie",
    "we mgle GPS ci nie pomoże. charakter tak",
  ],
  rain: [
    "leje jak w mordę. bierz kurtkę albo bądź twardy",
    "deszcz. sigma i tak biega, beta pisze do mamy",
    "mokro jak w komentach pod twoim postem",
    "kropi. weź parasol albo weź się w garść",
    "pada. świat płacze zamiast ciebie",
    "deszcz zmywa błoto, szkoda że nie wymówki",
    "mokro na zewnątrz, sucho w portfelu, klasyk",
    "deszcz nie pyta o zgodę, szef też nie będzie",
    "pada jak diabli, rusz się zanim się rozmyślisz",
    "krople na szybie, wymówki w głowie, no cap",
    "deszczowo, kaptur na głowę i chodu, sigma flow",
    "parasol zapomniany, charakter też",
    "deszcz to nie znak. to po prostu deszcz. idź",
    "mokro. buty wyschną, dzień nie wróci",
    "leje. dobra, bierz to na klatę i kurtkę",
    "kałuże omijasz, obowiązki też. sprytnie",
    "pada od rana. twoja dyscyplina od nigdy",
    "deszcz zmywa wszystko oprócz zaległości",
    "krople walą w dach głośniej niż twój budzik",
    "mokro jak w twoich planach na sobotę",
    "deszcz nie odwołał świata. siebie też nie",
    "parasol to nie tarcza charakteru, ale pomaga",
    "leje jak z cebra. najlepszy dzień na skupienie",
    "woda z nieba gratis. wymówki też, ale drożej",
  ],
  snow: [
    "śnieg. zimno jak serce twojej ex",
    "biało. jak konto po weekendzie",
    "śnieg, mróz, wymówki się nie liczą",
    "sypie. beta odwołuje plany, sigma pompki",
    "minus na termometrze, minus na koncie, spójność",
    "zimno jak relacje z rodziną od świąt",
    "śnieg sypie, ty śpisz, klasyczny beta scenariusz",
    "mróz szczypie mocniej niż wyciąg z konta",
    "biały puch, biała flaga twojego treningu",
    "zimno jak komentarze pod twoim biznesplanem",
    "śnieg pada równo, motywacja nierówno, idziemy",
    "zima nie negocjuje. ubierz się i wyjdź",
    "śnieg pokrywa wszystko. zaległości nie",
    "mróz testuje charakter. oblewasz co roku",
    "biało i cicho. idealne na myślenie, nie na sen",
    "zimno hartuje. o ile wyjdziesz z domu",
    "śnieg skrzypi pod butami. rusz te buty",
    "minus 5 na dworze, minus 10 w dyscyplinie",
    "łopata czeka. to też trening, nie narzekaj",
    "zimą widać kto ma plan, a kto ma koc",
    "śnieg pada na wszystkich równo. reszta zależy",
    "biało jak strona z twoimi osiągnięciami",
    "mróz. kawa gorąca, decyzje niech będą też",
    "zima trwa trzy miesiące. wymówki cały rok",
  ],
  thunder: [
    "burza. bogowie się jarają, ty się nie chowaj",
    "grzmi mocniej niż ego po jednej serii",
    "piorun i tak celuje w tego pod drzewem",
    "grzmot głośniejszy niż wymówki na czacie",
    "błyskawica szybsza niż twoja decyzja",
    "burza na niebie, chaos w planie dnia, standard",
    "błyskawica na niebie, zero w twoich decyzjach",
    "burza się zbliża, deadline też, oba ignorujesz",
    "grzmoty głośne, twoje 'zaraz zaczynam' głośniej",
    "burza. zamknij okno, otwórz laptopa, rób swoje",
    "piorun robi w sekundę tyle co ty w tydzień",
    "grzmi. natura ma więcej energii niż ty",
    "burza nie pyta o pozwolenie. ty pytasz o wszystko",
    "błysk, huk, trzy sekundy. tyle trwa twój zapał",
    "niebo się drze. ty się ogarnij",
    "burza przejdzie. twoje odkładanie zostanie",
    "piorun uderza raz. ty próbujesz piąty raz",
    "grzmot to nie wymówka, to soundtrack",
    "burza z gradem. idealnie na plan awaryjny",
    "elektryczność gratis, energia własna deficyt",
    "grzmi jak żołądek po fast foodzie zamiast obiadu",
    "burza czyści powietrze. ty poczyść grafik",
    "niebo ma więcej charakteru niż twój poniedziałek",
    "po burzy wychodzi słońce. po scrollu nie",
  ],
  night: [
    "noc. sigma trenuje, beta scrolluje reelsy",
    "3 w nocy i nie śpisz? peak male behavior",
    "księżyc świeci, a ty dalej sam. działaj albo śpij",
    "ciemno. dobra pora na refleksję czemu nie idzie",
    "północ, a ty w telefonie zamiast w łóżku, klasyk",
    "ciemno na zewnątrz, ciemno w głowie po scrollu",
    "gwiazdy świecą, ty gaśniesz, odwróć to jutro",
    "noc sowy, ale sowa ma plan na jutro",
    "śpij. jutro znowu udawaj że masz to ogarnięte",
    "ciemność na zewnątrz, jasność telefonu w oczy",
    "gwiazd nie widać w mieście, planów też nigdzie",
    "noc jak sumienie po piątym odcinku zamiast spać",
    "śpiulkolot się szykuje, jutro znów zaspane rel",
    "noc to nie wymówka na kolejny odcinek",
    "księżyc pracuje na nocną. ty na żadną",
    "o tej porze dobre decyzje już poszły spać",
    "2:00. jutrzejszy ty już cię nienawidzi",
    "cisza, ciemność, zero wymówek. śpij albo rób",
    "noc sprzyja myśleniu. nie scrollowaniu",
    "gwiazdy są dalej niż twoje cele. ale mają plan",
    "ciemno. najlepszy filtr na twoje odkładanie",
    "sen to nie słabość, to serwis. idź na przegląd",
    "północ minęła. ambicje poszły spać pierwsze",
    "noc kryje wszystko oprócz nieprzeczytanych maili",
  ],
};

export function pickSigma(kind: WeatherKind, isNight = false, seed = 0): string {
  const pool = isNight ? [...SIGMA.night, ...SIGMA[kind]] : SIGMA[kind];
  const idx = Math.abs(Math.floor(seed)) % pool.length;
  return pool[idx];
}
