// Generates src/lib/jokes.generated.ts from the Kotlin joke pools, which are
// the source of truth (the widget footer has the hard 50-character limit and
// the tests that enforce it). Run after editing any of them:
//
//   bun scripts/gen-jokes.ts
//
// Reads CleanJokes.kt and SigmaJokes.kt (Polish) and EnJokes.kt (English).
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dir, "..");
const widgetDir = join(root, "android/app/src/main/java/dev/pi0trdotsys/homebrewweather/widget");

/** Parses `private val NAME: Map<String, List<String>> = mapOf( "kind" to listOf("…", …), … )`. */
function parsePools(file: string, name: string): Record<string, string[]> {
  // Normalised: a Windows checkout has CRLF, and the patterns below expect \n.
  const src = readFileSync(join(widgetDir, file), "utf8").replace(/\r\n/g, "\n");
  const start = src.indexOf(`private val ${name}: Map<String, List<String>> = mapOf(`);
  if (start < 0) throw new Error(`${name} not found in ${file}`);
  const pools: Record<string, string[]> = {};
  let current: string[] | null = null;
  for (const line of src.slice(start).split("\n").slice(1)) {
    const key = line.match(/^\s+"(\w+)" to listOf\($/);
    if (key) {
      current = pools[key[1]] = [];
      continue;
    }
    const entry = line.match(/^\s+"((?:[^"\\]|\\.)*)",$/);
    if (entry && current) {
      current.push(entry[1].replace(/\\(["\\$])/g, "$1"));
      continue;
    }
    if (/^\s{4}\)$/.test(line)) break; // end of mapOf(
  }
  if (Object.keys(pools).length === 0) throw new Error(`no pools parsed for ${name}`);
  return pools;
}

const out = {
  PL_CLEAN: parsePools("CleanJokes.kt", "CLEAN"),
  PL_SIGMA: parsePools("SigmaJokes.kt", "SIGMA"),
  EN_CLEAN: parsePools("EnJokes.kt", "CLEAN"),
  EN_SIGMA: parsePools("EnJokes.kt", "SIGMA"),
};

const body = Object.entries(out)
  .map(([name, pools]) => `const ${name}: Pools = ${JSON.stringify(pools, null, 2)};`)
  .join("\n\n");

writeFileSync(
  join(root, "src/lib/jokes.generated.ts"),
  `// GENERATED by scripts/gen-jokes.ts from the Kotlin pools in
// android/app/src/main/java/dev/pi0trdotsys/homebrewweather/widget/
// (CleanJokes.kt, SigmaJokes.kt, EnJokes.kt). Do not edit by hand.
import type { WeatherKind } from "./wmo";
import type { Lang } from "./i18n";
import type { Tone } from "./settings";

type Pools = Record<string, string[]>;

${body}

/** Same pick rule as the widget (Jokes.pick): night lines mixed in after dark,
 * index = |seed| % pool size — so a given hour shows the same line in both. */
export function pickFooterJoke(tone: Tone, lang: Lang, kind: WeatherKind, isNight: boolean, seed: number): string {
  const pools =
    tone === "clean" ? (lang === "en" ? EN_CLEAN : PL_CLEAN) : lang === "en" ? EN_SIGMA : PL_SIGMA;
  const kindPool = pools[kind] ?? pools.cloud;
  const pool = isNight ? [...pools.night, ...kindPool] : kindPool;
  return pool[Math.abs(Math.floor(seed)) % pool.length];
}
`,
);
console.log(
  Object.entries(out)
    .map(([n, p]) => `${n}: ${Object.values(p).flat().length} lines`)
    .join(", "),
);
